notifications:
  email: false

language: c
sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local
  - $HOME/.stack

matrix:
  include:
  # cabal/linux
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=head CABALVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  # stack/linux use a pre-installed cabal-install for faster builds
  - env: BUILD=stack RESOLVER=lts-9.0 CABALVER=1.22
    addons: {apt: {packages: [libgmp-dev,cabal-install-1.22], sources: [hvr-ghc]}}

  - env: BUILD=stack RESOLVER=nightly CABALVER=2.0
    addons: {apt: {packages: [libgmp-dev,cabal-install-2.0], sources: [hvr-ghc]}}

  # cabal/stack/osx
  - env: BUILD=cabal RESOLVER=lts-9.0
    os: osx

  - env: BUILD=stack RESOLVER=lts-9.0
    os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head CABALVER=head
  - env: BUILD=stack RESOLVER=nightly

install: true
script:
  - |
    set_tool_path()  { eval "test -n \"\$$1\"" && eval "PATH=/opt/$2/\"\$$1\"/bin:$PATH"; true; }
    when_cabal() { if test "$BUILD" = cabal; then echo $1; fi; }
    script_url() { echo https://raw.githubusercontent.com/harendra-kumar/package-test/$1/package-test.sh; }

    CURL=$(which curl)
    PATH=/bin:/usr/bin
    # Add appropriate ghc and cabal versions from /opt to PATH
    set_tool_path GHCVER   ghc
    set_tool_path CABALVER cabal

  - env -i
      PATH=$PATH
      BUILD=$BUILD
      RESOLVER=$RESOLVER
      GHCVER=$GHCVER
      CABALVER=$CABALVER
      GHC_OPTIONS="-O0 -Werror"
      $(when_cabal CABAL_TEST_INSTALL=y)
      $(when_cabal CABAL_NO_SANDBOX=y)
      $(when_cabal CABAL_HACKAGE_MIRROR=hackage.haskell.org:http://hackage.fpcomplete.com)
      /bin/bash <($CURL -sL $(script_url 62db8f69afcb47428d1fb87ce4005b453f7f179c))
