notifications:
  email: false

language: c
sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local
  - $HOME/.stack

matrix:
  include:
  # cabal/linux
  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18
    addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=head CABALVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  # stack/linux
  - env: BUILD=stack RESOLVER=lts-6
    addons: {apt: {packages: [libgmp,libgmp-dev]}}

  - env: BUILD=stack RESOLVER=nightly
    addons: {apt: {packages: [libgmp,libgmp-dev]}}

  # cabal/stack/osx
  - env: BUILD=cabal RESOLVER=lts-6
    os: osx

  - env: BUILD=stack RESOLVER=lts-6
    os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head CABALVER=head
  - env: BUILD=stack RESOLVER=nightly

install: true
script:
  - |
    add_path()  { eval "test -n \"\$$1\"" && eval "PATH=/opt/$2/\"\$$1\"/bin:$PATH"; true; }
    cabal_env() { if test "$BUILD" = cabal; then echo $1; fi; }
    pkg_sanity() { echo https://raw.githubusercontent.com/harendra-kumar/package-sanity/$1/package-sanity.sh; }

    CURL=$(which curl)
    PATH=/bin:/usr/bin
    add_path GHCVER   ghc
    add_path CABALVER cabal

  - env -i
      PATH=$PATH
      BUILD=$BUILD
      RESOLVER=$RESOLVER
      GHCVER=$GHCVER
      CABALVER=$CABALVER
      GHC_OPTIONS="-O0 -Werror"
      $(cabal_env CABAL_TEST_INSTALL=y)
      $(cabal_env CABAL_NO_SANDBOX=y)
      $(cabal_env CABAL_HACKAGE_MIRROR=hackage.haskell.org:http://hackage.fpcomplete.com)
      /bin/bash <($CURL -sL $(pkg_sanity e912eac2ee7fc3dbf492f5e2d60db9f4425fbfa2))
